### ISSUE TITLE
jQuery script downloads could be upgraded to 3.2.1

### ISSUE THREAD

**Issue by platinumazure** [trhs-javascript-class/course-site-2017#3]
Version in our lesson plans: 3.1.0.

**Comment by weegeekps** [comment]
Are there any major changes? It's old but I don't see any harm in teaching an older version for the concepts.

**Comment by platinumazure** [comment]
I don't think so, I just figured we could update the references to be
current and not say anything about it in the class.

Nothing significant in 3.2 (we're on 3.1). So feel free to close if you
like.
